sudo: required
language: rust
rust:
  - 1.0.0
  - beta
  - nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo build &&
      RUST_TEST_THREADS=1 travis-cargo test &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo --only 1.0.0 doc-upload
  - travis-cargo coveralls
env:
  global:
    secure: OlWU0rTAKYV6NCHamtjs8GNYyBLd0x8xWTan482Da1zsWVIKFDEXjj2ymiTcz3SnDbTZWDnulsvQ2e/Cj8/7XogDcWmp73D3cxgHD2Glj5nZFdBHz+Gtt+bW5S0KYwnxv6UNmENcJZmRnIQDzSDVqkW6APKhJGUSJSRK4RCSk4I=
notifications:
    webhooks: http://huon.me:54856/travis
